name: caller workflow
on:
 workflow_dispatch
jobs:
  build:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
  steps:
    uses: Moni0104/task2/.github/workflows/task1.yml
      with:
      username: "monica"
