name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
jobs:
  example_job:
    name: Pass input
    runs-on: ubuntu-latest
    steps:
      - uses: ./github/workflows/test3.yml
        with:
          username: ${{ inputs.username }}     
  
  
  
