name: caller workflow
on:
 workflow_dispatch
jobs:
  call-workflow-passing-data:
    runs-on: ubuntu-latest
  steps:
    uses: Moni0104/task2/.github/workflows/test2.yml@main
    with:
      username: monica
